[build]
  command = "python -m pip install --no-cache-dir -r requirements.txt && cd openoperator-ui && npm install && npm run build"
  publish = "openoperator-ui/dist"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes should go to the backend functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"